### PR TITLE
Various metadata fixes

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Fix links in README.md and add CHANGELOG.md

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
@fumieval Could you enable issues on this repository? I'd like to move the backlog of issues from https://github.com/liyang/thyme over here and tidy things up further.

I'm happy to do the maintaining work if you give me permissions on GitHub / hackage for it.
Cheers

**Comment by fumieval** [comment]
Sorry for a delay, notifications on this repo has been disabled for some reason. I've just enabled issues

**Comment by tmcgilchrist** [comment]
Thank you.

**Comment by jamesdbrock** [comment]
Hey @fumieval I'm sure you've noticed already that this source repo is now in https://github.com/haskell-github-trust/thyme

@tmcgilchrist I sent you an invitation to join https://github.com/haskell-github-trust so now you can publish new versions of this package if you want to.

**Pull request merged**
